name: Matt Payne
favicon: null
layout_spectrum: 0.4866
typography_spectrum: 0.50972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d4dbe1'
    - '#a9aaae'
    - '#26252a'
    - '#5c6063'
  brandStrength: 0.03538714814931154
  lightness: 0.7371625662781298
  saturation: 0.990184381371364
  rhythmicContrast: 0.6429718669969589
purpose: []
